// demo-vue/app/components/App.vue
<template>
    <Page>
        <ActionBar title="Welcome to NativeScript-Vue!"/>
        <GridLayout columns="*" rows="*, auto">
            <Label class="message" :text="msg" col="0" row="0"/>
            <BottomBar row="1"
                v-on:tabSelected="tabSelected"
                v-bind:labelVisibility="labelVisibility"
                v-on:loaded="barLoaded">
                <BottomBarItem badgeBackgroundColor="green" badge="1" icon="res://ic_home_outline" title="Home 1" checkedIcon="res://ic_home_filled"></BottomBarItem>
                <BottomBarItem icon="res://ic_home_outline" badge="2" title="Home 2" checkedIcon="res://ic_home_filled"></BottomBarItem>
                <BottomBarItem icon="res://ic_home_outline" badge="3" title="Home 3" checkedIcon="res://ic_home_filled"></BottomBarItem>
            </BottomBar>
        </GridLayout>
    </Page>
</template>

<script>
  export default {
    methods: {
      tabSelected: function(event) {
          console.dir(event);
      },
      barLoaded: function(event) {
          console.dir(event);
      }
    },
    data: {
        labelVisibility: 0
    }
  }
</script>

<style scoped>
    ActionBar {
        background-color: #53ba82;
        color: #ffffff;
    }
    
    BottomBar {
        inactive-tint-color: #C34491;
        active-tint-color: #FFFFFF;
        bar-background-color: #9F489B;
        badge-background-color: #222222;
    }


    .message {
        vertical-align: center;
        text-align: center;
        font-size: 20;
        color: #333333;
    }
</style>

// demo-ng/src/app/app.component.ts
import { Component } from "@angular/core";
import { BottomBar } from 'nativescript-bottombar';

@Component({
    selector: "ns-app",
    moduleId: module.id,
    templateUrl: "./app.component.html",
    styles: [`
        BottomBar {
            inactive-tint-color: #C34491;
            active-tint-color: #FFFFFF;
            bar-background-color: #9F489B;
            badge-background-color: #222222;
        }
    `]
})
export class AppComponent {
    private bottomBar: BottomBar;

    home: string = 'Home bis';

    badgeValue: string = '1';

    tabSelected(event) {
        console.dir(event);
    }

    barLoaded(event) {
        this.bottomBar = event.object;

        setTimeout(() => {
            this.bottomBar.selectItem(1);
        }, 2000);
    }
}

<GridLayout rows="*, 49" class="page">
    <StackLayout row="0" orientation="vertical" backgroundColor="black">
        <Label text="demo"></Label>
    </StackLayout>
    <BottomBar row="1"
        (tabSelected)="tabSelected($event)"
        [labelVisibility]="labelVisibility"
        (loaded)="barLoaded($event)">
        <BottomBarItem badgeBackgroundColor="green" badge="1" icon="res://ic_home_outline" title="Home 1" checkedIcon="res://ic_home_filled"></BottomBarItem>
        <BottomBarItem icon="res://ic_home_outline" badge="2" title="Home 2" checkedIcon="res://ic_home_filled"></BottomBarItem>
        <BottomBarItem icon="res://ic_home_outline" badge="3" title="Home 3" checkedIcon="res://ic_home_filled"></BottomBarItem>
    </BottomBar>
</GridLayout>
